= FSx for ONTAPファイルシステムをBlueXPのワークスペースに関連付ける
:allow-uri-read: 




=== FSx for ONTAPファイルシステムをBlueXPのワークスペースに関連付ける

2024 年 11 月のBlueXP統合後、新しく作成された FSx for ONTAPファイル システムはBlueXP内の 1 つのワークスペースに関連付けられていませんでした。  FSx for ONTAPファイル システムを作成または検出すると、それらはBlueXPアカウント内の 1 つのワークスペースに関連付けられるようになりました。

ワークスペースに関連付けられていない既存の FSx for ONTAPファイル システムがある場合は、 BlueXPでそれらをワークスペースに関連付けるお手伝いをします。あなたはできるlink:https://docs.netapp.com/us-en/bluexp-setup-admin/task-get-help.html#create-a-case-with-netapp-support["NetAppサポートにケースを作成する"^]BlueXPコンソール内から。サービスとして*Workload Factory*を選択します。



=== BlueXPキャンバスからのファイルシステムの削除

BlueXPキャンバスのワークスペースから FSx for ONTAPファイル システムを削除できるようになりました。この操作により、ファイル システムと 1 つのワークスペースの関連付けが解除され、同じBlueXPアカウント内の別のワークスペースに関連付けることができるようになります。

link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-remove-filesystem.html["BlueXPのワークスペースから FSx for ONTAPファイルシステムを削除する方法を学びます"^]



=== 監視および追跡操作に使用できるトラッカー

新しい監視機能である Tracker が、 BlueXP Amazon FSx for NetApp ONTAPで利用可能になりました。  Tracker を使用すると、資格情報、ストレージ、リンク操作の進行状況とステータスを監視および追跡したり、操作タスクとサブタスクの詳細を確認したり、問題や障害を診断したり、失敗した操作のパラメータを編集したり、失敗した操作を再試行したりできます。

link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-monitor-operations.html["BlueXPで FSx for ONTAP操作を監視および追跡する方法を学びます"^]



=== CloudShell はBlueXPワークロードで利用可能

CloudShell は、 BlueXPコンソール内のBlueXPワークロードで利用できます。  CloudShell を使用すると、 BlueXPアカウントで指定した AWS およびONTAP認証情報を使用して、シェルのような環境で AWS CLI コマンドまたはONTAP CLI コマンドを実行できます。

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["CloudShellを使用する"^]
