---
sidebar: sidebar 
permalink: use/task-replicate-data.html 
keywords: amazon fsx for netapp ontap, fsx, manage fsx for ontap system, delete fsx for ontap system, remove fsx for ontap system, throughput capacity, change throughput, automatic capacity management, capacity management, storage capacity, replication, classification, sync, backup, recovery, bluexp, NetApp Console 
summary: NetApp Consoleで FSx for ONTAPシステムを作成または検出すると、ファイルシステムを管理し、バックアップやリカバリなどの機能を提供するNetAppデータ サービスを使用できるようになります。 
---
= NetApp ConsoleでFSx for ONTAPデータをレプリケートする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データが保存されている地域で災害が発生した場合に、データの損失を防ぐためにデータを複製します。データレプリケーションは、Amazon FSx for NetApp ONTAPファイルシステムとオンプレミスONTAPシステムまたはCloud Volumes ONTAP間でサポートされています。

.タスク概要
この操作は、FSx for ONTAP ファイルシステム、オンプレミス ONTAP システム、または Cloud Volumes ONTAP システムのソースボリュームのレプリケーション関係を作成します。

ターゲット ファイル システム内の複製されたボリュームはデータ保護（DP）ボリュームであり、次の命名形式に従います： `{OriginalVolumeName}_copy`

.開始する前に
始める前に次の点を考慮してください。

* FSx for ONTAP とオンプレミス ONTAP または Cloud Volumes ONTAP 間でデータを複製するには、ファイル システムに接続できる Console エージェントを選択するか、リンクを関連付けるファイル システムを入力する必要があります。link:https://docs.netapp.com/us-en/workload-fsx-ontap/links-overview.html["リンクの使用について学ぶ"^]
* 使用可能、作成済み、または構成ミス以外の状態のボリュームではレプリケーションはサポートされません。また、ONTAP バージョンに互換性がない場合もサポートされません。


.手順
. NetApp Console の Systems ページから、ソース FSx for ONTAP ファイル システム、オンプレミス ONTAP システム、または Cloud Volumes ONTAP システムをターゲット FSx for ONTAP ファイル システムの上にドラッグし、*レプリケーション*を選択します。
. レプリケーションの作成ページで、レプリケートするソースボリュームを選択し、[次へ] をクリックします。
. レプリケーション ターゲットで、次の内容を入力します。
+
.. *ターゲット名*：ソース ストレージ システムをコンソール システム ページのターゲット システムにドラッグアンドドロップしたときに適用したターゲット名。
.. *使用ケース*: レプリケーションの次の使用ケースのいずれかを選択します。選択したユースケースに応じて、Workload Factory はベストプラクティスに従って推奨値をフォームに入力します。フォームに入力する際に、推奨値を受け入れることも、変更することもできます。
+
*** 移行: データをターゲットの FSx for ONTAPファイルシステムに転送します
*** ホット災害復旧: 重要なワークロードの高可用性と迅速な災害復旧を保証します
*** コールドまたはアーカイブ災害復旧:
+
**** コールド災害復旧: より長い復旧時間目標 (RTO) と復旧ポイント目標 (RPO) を使用してコストを削減します。
**** アーカイブ: 長期保存とコンプライアンスのためにデータを複製します


*** その他
+
さらに、ユースケースの選択によって、レプリケーション ポリシー、またはSnapMirrorポリシー (ONTAP) が決まります。レプリケーションポリシーを説明するために使用される用語は、link:https://docs.netapp.com/us-en/ontap/data-protection/default-protection-policies-concept.html["ONTAP 9 ドキュメント"^] 。

+
**** 移行などの場合、レプリケーション ポリシーは _MirrorAllSnapshots_ と呼ばれます。  _MirrorAllSnapshots_ は、すべてのスナップショットと最新のアクティブなファイルシステムをミラーリングするための非同期ポリシーです。
**** ホット、コールド、またはアーカイブの災害復旧の場合、レプリケーション ポリシーは _MirrorAndVault_ と呼ばれます。  _MirrorAndVault_ は、最新のアクティブなファイル システムと毎日および毎週のスナップショットをミラーリングするための非同期およびボールト ポリシーです。
+
すべてのユースケースにおいて、長期保存用にスナップショットを有効にすると、デフォルトのレプリケーション ポリシーは _MirrorAndVault_ になります。





.. *FSx for ONTAP ファイル システム*：ターゲット FSx for ONTAP ファイル システムのクレデンシャル、リージョン、および FSx for ONTAP ファイル システム名を選択します。
.. *ストレージ VM 名*: ドロップダウン メニューからストレージ VM を選択します。選択したストレージ VM は、このレプリケーション関係で選択されたすべてのボリュームのターゲットになります。
.. *ボリューム名*: ターゲットボリューム名は次の形式で自動的に生成されます `{OriginalVolumeName}_copy`。自動生成されたボリューム名を使用することも、別のボリューム名を入力することもできます。
.. *階層化ポリシー*: ターゲット ボリュームに保存されているデータの階層化ポリシーを選択します。階層化ポリシーは、選択したユースケースに推奨される階層化ポリシーにデフォルト設定されます。
+
_バランス (自動)_ は、Workload Factory コンソールを使用してボリュームを作成するときのデフォルトの階層化ポリシーです。ボリューム階層化ポリシーの詳細については、以下を参照してください。link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["ボリュームストレージ容量"^] AWS FSx for NetApp ONTAPドキュメント。ワークロード ファクトリーは、ワークロード ファクトリー コンソールで階層化ポリシーにユースケース ベースの名前を使用し、括弧内に FSx for ONTAP階層化ポリシー名を含めることに注意してください。

+
移行ユースケースを選択した場合、Workload Factory はソース ボリュームの階層化ポリシーをターゲット ボリュームにコピーすることを自動的に選択します。階層化ポリシーのコピーの選択を解除し、レプリケーション対象として選択したボリュームに適用する階層化ポリシーを選択できます。

.. *最大転送速度*: *制限* を選択し、最大転送制限を MB/秒単位で入力します。または、「*無制限*」を選択します。
+
制限がないと、ネットワークとアプリケーションのパフォーマンスが低下する可能性があります。あるいは、災害復旧を主目的として使用するような重要なワークロードの場合、FSx for ONTAPファイル システムに無制限の転送速度を使用することをお勧めします。



. レプリケーション設定で、次の内容を入力します。
+
.. *レプリケーション間隔*: スナップショットがソース ボリュームからターゲット ボリュームに転送される頻度を選択します。
.. *長期保存*: 必要に応じて、長期保存用のスナップショットを有効にします。長期保存により、サイト全体の障害が発生した場合でもビジネス サービスは継続して実行でき、セカンダリ コピーを使用してアプリケーションを透過的にフェールオーバーできます。
+
長期保存のないレプリケーションでは、_MirrorAllSnapshots_ ポリシーが使用されます。長期保存を有効にすると、レプリケーションに _MirrorAndVault_ ポリシーが割り当てられます。

+
長期保存を有効にする場合は、既存のポリシーを選択するか、新しいポリシーを作成して、複製するスナップショットと保持する数を定義します。

+

NOTE: 長期保存には、ソース ラベルとターゲット ラベルの一致が必要です。必要に応じて、ワークロード ファクトリーで不足しているラベルを作成できます。

+
*** *既存のポリシーを選択*: ドロップダウン メニューから既存のポリシーを選択します。
*** *新しいポリシーを作成*：*ポリシー名*を入力します。


.. *不変のスナップショット*: オプション。このポリシーで作成されたスナップショットが保持期間中に削除されないようにするには、「*不変スナップショットを有効にする*」を選択します。
+
*** *保存期間*を時間、日、月、または年数で設定します。
*** *スナップショット ポリシー*: 表で、スナップショット ポリシーの頻度と保持するコピーの数を選択します。複数のスナップショット ポリシーを選択できます。


.. *S3アクセスポイント*：オプションで、S3アクセスポイントを接続して、AWS S3 APIを介してNFSまたはSMB/CIFSボリューム上に存在するFSx for ONTAPファイルシステムデータにアクセスします。ファイルアクセスタイプのみがサポートされます。以下の詳細を入力します（
+
*** *S3 アクセス ポイント名*：S3 アクセス ポイントの名前を入力します。
*** *User*：ボリュームへのアクセス権を持つ既存のユーザーを選択するか、新しいユーザーを作成します。
*** *ユーザー タイプ*：ユーザー タイプとして *UNIX* または *Windows* を選択します。
*** *ネットワーク構成*：*インターネット* または *仮想プライベート クラウド (VPC)* を選択します。選択するネットワークの種類によって、アクセス ポイントがインターネットからアクセスできるか、特定の VPC に制限されるかが決まります。
*** *メタデータを有効にする*：メタデータを有効にすると、S3 アクセス ポイントからアクセスできるすべてのオブジェクトを含む S3 テーブルが作成され、監査、ガバナンス、自動、分析、最適化に使用できるようになります。メタデータを有効にすると追加の AWS コストが発生します。詳細については、link:https://aws.amazon.com/s3/pricing/["Amazon S3 価格設定ドキュメント"^]を参照してください。


.. *S3 アクセス ポイント タグ*：オプションで、最大 50 個のタグを追加できます。




. *作成*を選択します。

