---
sidebar: sidebar 
permalink: use/task-manage-fsx-systems.html 
keywords: amazon fsx for netapp ontap, fsx, manage fsx for ontap system, delete fsx for ontap system, remove fsx for ontap system, throughput capacity, change throughput, automatic capacity management, capacity management, storage capacity, replication, classification, sync, backup, recovery, NetApp Console 
summary: NetApp Consoleで FSx for ONTAPシステムを作成または検出すると、ファイルシステムを管理し、バックアップやリカバリなどの機能を提供するNetAppデータ サービスを使用できるようになります。 
---
= Amazon FSx for NetApp ONTAP ファイルシステムの管理
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Consoleで FSx for ONTAPシステムを作成または検出した後、ボリュームの作成、ストレージ VM の管理、データの保護、ファイル システムの管理を行うことで、ファイル システムを管理できます。コンソールを使用すると、バックアップとリカバリ、データ分類、データ同期などの機能を提供するデータ サービスも使用できます。



[[manage-a-file-system-using-netapp-workload-factory]]
== NetApp Workload Factoryを使用してファイルシステムを管理する

FSx for ONTAPシステムをNetApp ConsoleのSystemsページから開くと、NetApp Workload Factoryに移動します。NetApp Workload Factoryは、業界のベストプラクティスを使用してAmazon FSx for NetApp ONTAPで主要なワークロードを計画、プロビジョニング、運用するインテリジェントな最適化および自動化サービスです。

https://docs.netapp.com/us-en/workload-fsx-ontap/index.html["NetApp Workload Factoryを使用してファイルシステムを管理する方法を学びます"^]



[[manage-a-file-system-using-ontap-system-manager]]
== ONTAP System Managerを使用してファイルシステムを管理する

ONTAP System Manager インターフェイスを使用して、コンソールから FSx for ONTAPファイル システムを直接管理できます。System Manager を使用するには、コンソールエージェントまたは AWS Lambda リンクが必要です。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/links-overview.html["リンクの使用について学ぶ"^]



[[manage-a-file-system-using-amazon-cloudformation]]
== Amazon CloudFormation を使用してファイルシステムを管理する

Amazon CloudFormation を使用して、FSx for ONTAPファイルシステムリソース (ボリューム、CIFS 共有、エクスポートポリシーなど) をプロビジョニングおよび管理できます。

link:https://github.com/NetApp/NetApp-CloudFormation-FSx-ONTAP-provider["NetApp CloudFormation FSx for ONTAPプロバイダー GitHub リポジトリ"^]



[[use-netapp-data-services-with-a-file-system]]
== ファイルシステムでNetAppデータサービスを使用する

NetAppデータ サービスを FSx for ONTAPファイル システムと共に使用して、データのバックアップとリカバリ、データの転送と同期、データのスキャンと分類、データの複製、アクセスの高速化、トラフィックのオフロードなどを行うことができます。



[[back-up-and-recover-your-data]]
=== データのバックアップと復元

NetApp Backup and Recovery は、オンプレミスとクラウドの両方で、 NetApp ONTAPデータ、データベース、仮想マシンに対して効率的で安全かつコスト効率に優れたデータ保護を提供します。

link:https://docs.netapp.com/us-en/data-services-backup-recovery/index.html["NetApp Backup and Recoveryの使用を開始する"^]



[[transfer-and-synchronize-data]]
=== データの転送と同期

NetApp Copy and Sync は、オンプレミスとクラウド オブジェクト ストア間で NAS データを転送するためのクラウド レプリケーションおよび同期サービスです。

link:https://docs.netapp.com/us-en/data-services-copy-sync/task-quick-start.html["NetApp Copy and Syncを使い始める"^]



[[scan-and-classify-your-data]]
=== データをスキャンして分類する

NetApp Data Classification を使用すると、組織のハイブリッド マルチクラウド全体のデータをスキャンして分類できます。

link:https://docs.netapp.com/us-en/data-services-data-classification/index.html["NetApp Data Classificationを使い始める"^]



[[speed-up-access-or-offload-traffic]]
=== アクセスを高速化したりトラフィックをオフロードしたりする

NetApp Volume Cachingは、リモートの場所に永続的な書き込み可能なボリュームを提供します。ボリューム キャッシュを使用すると、データへのアクセスを高速化したり、頻繁にアクセスされるボリュームのトラフィックを軽減したりできます。

link:https://docs.netapp.com/us-en/console-volume-caching/get-started/cache-intro.html["NetApp Volume Cachingを使い始める"^]
