---
sidebar: sidebar 
permalink: use/task-monitor-operations.html 
keywords: monitor jobs, track jobs, monitor, track, NetApp Console, bluexp 
summary: NetAppコンソールの Tracker を使用して、FSx for ONTAP操作を追跡し、操作の進行状況を監視します。 
---
= NetAppコンソールの Tracker を使用して FSx for ONTAP操作を監視する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetAppコンソールの Tracker を使用して、FSx for ONTAP操作の実行を監視および追跡し、ジョブの進行状況を監視します。

.タスク概要
NetAppコンソールには、ジョブ監視機能の Tracker が用意されており、資格情報、FSx for ONTAP、リンク操作の進行状況とステータスを監視および追跡したり、操作タスクとサブタスクの詳細を確認したり、問題や障害を診断したりできます。

Tracker ではいくつかのアクションが利用できます。ジョブを期間 (過去 24 時間、7 日間、14 日間、または 30 日間)、ワークロード、ステータス、ユーザーでフィルタリングしたり、検索機能を使用してジョブを検索したり、ジョブ テーブルを CSV ファイルとしてダウンロードしたりできます。トラッカーはいつでも更新できます。また、失敗した操作をすぐに再試行したり、失敗した操作のパラメータを編集して操作を再試行したりすることもできます。

Tracker は操作に応じて 2 つのレベルの監視をサポートします。ファイル システムの展開などの各タスクには、タスクの説明、ステータス、開始時刻、タスクの期間、ユーザー、リージョン、プロキシ リソース、タスク ID、および関連するすべてのサブタスクが表示されます。  API 応答を表示して、操作中に何が起こったかを理解できます。

トラッカーのタスクレベルと例::
+
--
* レベル 1 (親タスク): ファイル システムの展開を追跡します。
* レベル 2 (サブタスク): ファイル システムの展開に関連するサブタスクを追跡します。


--
操作状況:: Tracker での操作ステータスは、_進行中_、_成功_、_失敗_ のいずれかになります。
動作周波数:: 操作頻度はタスクの種類とスケジュールによって異なります。
イベントの保持:: イベントはユーザー インターフェースに 30 日間保持されます。




== 操作の追跡と監視

Tracker を使用してNetAppコンソールでの操作を追跡および監視します。

.手順
. NetAppコンソール メニューから、*ワークロード* を選択し、次に *管理* を選択します。
. 管理メニューから*トラッカー*を選択します。
. トラッカーでは、タスクを表示したり、フィルターや検索を使用して結果を絞り込んだりできます。  *CSV エクスポート* を選択して、すべての操作のレポートをダウンロードすることもできます。




== APIリクエストを表示

Tracker のタスクの Codebox で API リクエストを表示します。

.手順
. トラッカーでタスクを選択します。
. 3 つのドットのメニューを選択し、*API リクエストの表示* を選択します。




== 失敗した操作を再試行する

Tracker で失敗した操作を再試行します。失敗した操作を再試行すると、Tracker で監視できる新しいタスクが開始されます。

失敗した操作のエラー メッセージをコピーすることもできます。


NOTE: 失敗した操作は 1 回だけ再試行できます。

.手順
. トラッカーで、失敗した操作を選択します。
. 3 つのドットのメニューを選択し、[再試行] を選択します。


.結果
操作が再開され、Tracker に新しいタスクとして表示されます。



== 失敗した操作を編集して再試行する

失敗した操作のパラメータを編集し、Tracker の外部で操作を再試行します。

.手順
. トラッカーで、失敗した操作を選択します。
. 3 つのドットのメニューを選択し、[編集して再試行] を選択します。
+
ボリューム作成などの操作ページにリダイレクトされ、そこでパラメータを編集して操作を再試行できます。



.結果
操作が再開されます。操作のステータスを表示するには、トラッカーに移動してください。
