---
sidebar: sidebar 
permalink: use/task-create-fsx-system.html 
keywords: Amazon FSx for NetApp ONTAP, fsx, volumes, create system, delete system, access key, secret key, region, working environment, availability zones, discover, storage capacity, iops, throughput, security group, security, bluexp, NetApp Console 
summary: NetApp Consoleからボリュームと追加のデータ サービスを追加および管理するには、FSx for ONTAPファイル システムを作成または検出します。 
---
= FSx for ONTAPファイルシステムを作成または検出する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Consoleからボリュームと追加のデータ サービスを追加および管理するには、FSx for ONTAPファイル システムを作成または検出します。



== FSx for ONTAPシステムを作成する

最初のステップは、FSx for ONTAPファイル システムを作成することです。  AWSマネジメントコンソールでFSx for ONTAPファイルシステムをすでに作成している場合は、link:task-create-fsx-system.html#discover-an-existing-fsx-for-ontap-file-system["NetApp Consoleを使用して検出する"] 。

.タスク概要
ファイル システムを作成すると、ストレージ VM が作成されます。

.開始する前に
FSx for ONTAPファイルシステムを作成する前に、次のものが必要です。

* FSx for ONTAPファイルシステムを作成するために必要な権限を Workload Factory に付与する IAM ロールの ARN。link:../requirements/task-setting-up-permissions-fsx.html["AWSアカウントに権限を付与する方法を学ぶ"^] 。
* FSx for ONTAPインスタンスを作成するリージョンと VPC 情報。




== FSx for ONTAPファイルシステムを作成する

_クイック作成_ または _高度な作成_ を使用して、FSx for ONTAPファイル システムを作成できます。 Codebox で利用可能な REST API、CloudFormation、Terraform などのツールも使用できます。link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html#how-to-use-codebox["Codebox を使って自動化する方法を学ぶ"^] 。


NOTE: CodeboxからTerraformを使用する場合、コピーまたはダウンロードしたコードは `fsxadmin`そして `vsadmin`パスワード。コードを実行するときにパスワードを再入力する必要があります。

[role="tabbed-block"]
====
.クイック作成
--
クイック作成を使用すると、推奨されるベスト プラクティス構成を使用できます。  FSx for ONTAPファイル システムを作成した後、ほとんどの設定を変更できます。

.手順
. NetApp Consoleメニューから、*ストレージ* を選択し、次に *管理* を選択します。
. システム ページから *システムの追加* を選択します。
. 場所として *Amazon Web Services* を選択し、 Amazon FSx for NetApp ONTAPの *新規追加* を選択します。
. FSx for ONTAPファイル システムの作成ページで、*クイック作成*を選択します。
+
保存した構成を読み込むこともできます。

. ファイル システムの一般構成で、次の内容を入力します。
+
.. *AWS 認証情報*: AWS 認証情報を追加するか、認証情報なしで続行するかを選択します。資格情報がなくても、Codebox から部分的に完成したコードをコピーしてダウンロードできます。コードはテンプレートのように使用でき、不足している情報 (資格情報など) を入力したり、コードを実行する前に特定のデータをカスタマイズしたりできます。
.. *ファイルシステム名*: ファイルシステムの名前を入力します。
.. *デプロイメント トポロジ*: デプロイメント トポロジを選択します。
+
*** スケールアップ トポロジでは、1 つのファイル システムがデータ配布に使用され、データの増加に対応するためにサイズを増やすことができます。
*** スケールアウト トポロジでは、データの分散に複数のファイル システムが使用されます。


.. *HA ペア*: HA ペアの数を入力します。
+
*** スケールアップ展開の場合、HA ペアは 1 つだけ使用できます。
*** スケールアウト展開の場合、2 ～ 12 個の HA ペアを使用できます。


.. *展開タイプ*: 展開タイプを選択します。
+
*** 単一可用性ゾーン (Single-AZ) 展開: ハードウェア障害を監視し、障害発生時にインフラストラクチャ コンポーネントを自動的に交換することで、可用性を確保します。コンポーネント障害からデータを保護するために、アベイラビリティーゾーン内でデータを自動的に複製することで、高い耐久性を実現します。
*** 複数のアベイラビリティゾーン (マルチ AZ) 配置: アベイラビリティゾーンが利用できない場合でも、データの継続的な可用性を提供します。マルチ AZ ファイル システムは、シングル AZ ファイル システムのすべての可用性と耐久性の機能をサポートします。マルチ AZ ファイル システムは、共有ONTAPファイル データに対する高可用性を必要とし、アベイラビリティ ゾーン全体にわたる組み込みレプリケーションを備えたストレージを必要とする、ビジネス クリティカルな本番ワークロード向けに設計されています。


.. *タグ*: オプションで、最大 50 個のタグを追加できます。


. *ネットワークとセキュリティ*の*リージョンとVPC*フィールドで、ファイル システムのリージョンとVPCを選択します。
. *ファイル システムの詳細* で、次の情報を入力します。
+
.. *SSD ストレージ容量*: ストレージ容量を入力し、ストレージ容量の単位を選択します。
.. * ONTAP資格情報*: ONTAPユーザー名とパスワードを入力します。
.. *SMB/CIFS セットアップ*: オプション。 SMB/CIFS プロトコルを使用してボリュームにアクセスする場合は、ファイル システムの作成時にストレージ VM の Active Directory を構成する必要があります。このファイル システム用に作成されたストレージ VM の次の詳細を指定します。
+
... *参加する Active Directory ドメイン*: Active Directory の完全修飾ドメイン名 (FQDN) を入力します。
... *DNS IP アドレス*: 最大 3 つの DNS IP アドレスをカンマで区切って入力します。
... *SMB サーバー NetBIOS 名*: ストレージ VM 用に作成する Active Directory コンピュータ オブジェクトの SMB サーバー NetBIOS 名を入力します。これは、Active Directory 内のこのストレージ VM の名前です。
... *ユーザー名*: 既存の Active Directory 内のサービス アカウントのユーザー名を入力します。
+
ドメインのプレフィックスまたはサフィックスを含めないでください。のために `EXAMPLE\ADMIN`、 使用 `ADMIN`。

... *パスワード*: サービス アカウントのパスワードを入力します。
... *組織単位*: オプションで、FSx for ONTAPのコンピュータ アカウントを作成する組織単位の名前を入力します。  OU は、ファイル システムに参加する組織単位の識別パス名です。
... *委任された管理者グループ*: オプションで、ファイル システムを管理できる Active Directory 内のグループの名前を入力します。
+
AWS Managed Microsoft AD を使用している場合は、AWS Delegated FSx Administrators、AWS Delegated Administrators、または OU への委任された権限を持つカスタムグループなどのグループを指定する必要があります。

+
自己管理型 AD に参加する場合は、AD 内のグループの名前を使用します。デフォルトのグループは `Domain Admins`。





. *概要*を開いて、定義した構成を確認します。必要に応じて、ファイル システムを保存または作成する前に、この時点で設定を変更できます。
. ファイル システムを保存または作成します。


.結果
ファイルシステムを作成した場合、新しい FSx for ONTAP構成が [システム] ページに表示されます。

FSx for ONTAPファイルシステムは、 NetApp Consoleのワークロード、 ONTAP System Manager、AWS CloudFormation など、いくつかの方法で管理できます。。 link:task-manage-fsx-systems.html["FSx for ONTAPファイルシステムを管理する"] 。

--
.高度な作成
--
詳細作成では、可用性、セキュリティ、バックアップ、メンテナンスなどのすべての構成オプションを設定します。

.手順
. NetApp Consoleメニューから、*ストレージ* を選択し、次に *管理* を選択します。
. システム ページから *システムの追加* を選択します。
. 場所として *Amazon Web Services* を選択し、 Amazon FSx for NetApp ONTAPの *新規追加* を選択します。
. FSx for ONTAP の作成ページで、*高度な作成*を選択します。
+
保存した構成を読み込むこともできます。

. ファイル システムの一般構成で、次の内容を入力します。
+
.. *AWS 認証情報*: Workload Factory に AWS 認証情報を追加するか、認証情報なしで続行するかを選択します。
.. *ファイルシステム名*: ファイルシステムの名前を入力します。
.. *デプロイメント トポロジ*: デプロイメント トポロジを選択します。
+
*** スケールアップ トポロジでは、1 つのファイル システムがデータ配布に使用され、データの増加に対応するためにサイズを増やすことができます。
*** スケールアウト トポロジでは、データの分散に複数のファイル システムが使用されます。


.. *HA ペア*: HA ペアの数を入力します。
+
*** スケールアップ展開の場合、HA ペアは 1 つだけ使用できます。
*** スケールアウト展開の場合、2 ～ 12 個の HA ペアを使用できます。


.. *展開タイプ*: 展開タイプを選択します。
+
*** 単一可用性ゾーン (Single-AZ) 展開: ハードウェア障害を監視し、障害発生時にインフラストラクチャ コンポーネントを自動的に交換することで、可用性を確保します。コンポーネント障害からデータを保護するために、アベイラビリティーゾーン内でデータを自動的に複製することで、高い耐久性を実現します。
*** 複数のアベイラビリティゾーン (マルチ AZ) 配置: アベイラビリティゾーンが利用できない場合でも、データの継続的な可用性を提供します。マルチ AZ ファイル システムは、シングル AZ ファイル システムのすべての可用性と耐久性の機能をサポートします。マルチ AZ ファイル システムは、共有ONTAPファイル データに対する高可用性を必要とし、アベイラビリティ ゾーン全体にわたる組み込みレプリケーションを備えたストレージを必要とする、ビジネス クリティカルな本番ワークロード向けに設計されています。


.. *タグ*: オプションで、最大 50 個のタグを追加できます。


. [ネットワークとセキュリティ] で、次の情報を入力します。
+
.. *リージョンと VPC*: ファイル システムのリージョンと VPC を選択します。
.. *セキュリティ グループ*: セキュリティ グループを作成するか、既存のセキュリティ グループを使用します。
.. *可用性ゾーン*: 可用性ゾーンとサブネットを選択します。
+
*** クラスター構成ノード 1 の場合: 可用性ゾーンとサブネットを選択します。
*** クラスター構成ノード 2 の場合: 可用性ゾーンとサブネットを選択します。


.. *VPC ルート テーブル*: ボリュームへのクライアント アクセスを有効にするには、VPC ルート テーブルを選択します。
.. *エンドポイント IP アドレス範囲*: *VPC 外のフローティング IP アドレス範囲* を選択するか、*IP アドレス範囲を入力* して IP アドレス範囲を入力します。
.. *暗号化*: ドロップダウンから暗号化キー名を選択します。


. ファイル システムの詳細で、次の情報を入力します。
+
.. *SSD ストレージ容量*: ストレージ容量を入力し、ストレージ容量の単位を選択します。
.. *プロビジョニングされた IOPS*: *自動* または *ユーザーによるプロビジョニング* を選択します。
.. *HA ペアあたりのスループット容量*: HA ペアあたりのスループット容量を選択します。
.. * ONTAP資格情報*: ONTAPユーザー名とパスワードを入力します。
.. *ストレージ VM 資格情報*: ユーザー名を入力します。パスワードはこのファイル システムに固有のものにすることも、 ONTAP認証情報に入力したものと同じパスワードを使用することもできます。
.. *SMB/CIFS セットアップ*: オプション。 SMB/CIFS プロトコルを使用してボリュームにアクセスする場合は、ファイル システムの作成時にストレージ VM の Active Directory を構成する必要があります。このファイル システム用に作成されたストレージ VM の次の詳細を指定します。
+
... *参加する Active Directory ドメイン*: Active Directory の完全修飾ドメイン名 (FQDN) を入力します。
... *DNS IP アドレス*: 最大 3 つの DNS IP アドレスをカンマで区切って入力します。
... *SMB サーバー NetBIOS 名*: ストレージ VM 用に作成する Active Directory コンピュータ オブジェクトの SMB サーバー NetBIOS 名を入力します。これは、Active Directory 内のこのストレージ VM の名前です。
... *ユーザー名*: 既存の Active Directory 内のサービス アカウントのユーザー名を入力します。
+
ドメインのプレフィックスまたはサフィックスを含めないでください。のために `EXAMPLE\ADMIN`、 使用 `ADMIN`。

... *パスワード*: サービス アカウントのパスワードを入力します。
... *組織単位*: オプションで、FSx for ONTAPのコンピュータ アカウントを作成する組織単位の名前を入力します。  OU は、ファイル システムに参加する組織単位の識別パス名です。
... *委任された管理者グループ*: オプションで、ファイル システムを管理できる Active Directory 内のグループの名前を入力します。
+
AWS Managed Microsoft AD を使用している場合は、AWS Delegated FSx Administrators、AWS Delegated Administrators、または OU への委任された権限を持つカスタムグループなどのグループを指定する必要があります。

+
自己管理型 AD に参加する場合は、AD 内のグループの名前を使用します。デフォルトのグループは `Domain Admins`。





. 「バックアップとメンテナンス」で、次の情報を入力します。
+
.. *FSx for ONTAPバックアップ*: 毎日の自動バックアップはデフォルトで有効になっています。必要に応じて無効にします。
+
... *自動バックアップの保持期間*: 自動バックアップを保持する日数を入力します。
... *毎日の自動バックアップ ウィンドウ*: *指定なし* (毎日のバックアップの開始時刻が自動的に選択されます) または *毎日のバックアップの開始時刻を選択* のいずれかを選択し、開始時刻を指定します。
... *週次メンテナンス ウィンドウ*: *指定なし* (週次メンテナンス ウィンドウの開始時刻が自動的に選択されます) または *30 分間の週次メンテナンス ウィンドウの開始時刻を選択* のいずれかを選択し、開始時刻を指定します。




. ファイル システムを保存または作成します。


.結果
ファイルシステムを作成した場合、新しい FSx for ONTAP構成が [システム] ページに表示されます。

FSx for ONTAPファイルシステムは、 NetApp Consoleのワークロード、 ONTAP System Manager、AWS CloudFormation など、いくつかの方法で管理できます。。 link:task-manage-fsx-systems.html["FSx for ONTAPファイルシステムを管理する"] 。

--
====


== 既存の FSx for ONTAPファイルシステムを検出する

以前にNetApp Consoleで AWS 認証情報を指定している場合は、 [Discoverable systems]ページから FSx for ONTAPファイルシステムを自動的に検出できます。利用可能なデータ サービスを確認することもできます。

.タスク概要
FSx for ONTAPファイル システムはアカウント内で 1 回だけ検出し、1 つのワークスペースに接続できます。ファイル システムは後で削除して、別のワークスペースに再度関連付けることができます。

.手順
. NetApp Consoleメニューから、*ストレージ*、*管理*、*Discoverable systems*の順に選択します。
. 検出された FSx for ONTAPファイル システムの数が表示されます。*Discover*を選択します。
. 1 つまたは複数のファイル システムを選択し、[*検出*] を選択して、それらをシステム ページに追加します。


[NOTE]
====
* 名前のないクラスターを選択した場合は、クラスターの名前を入力するプロンプトが表示されます。
* コンソールから FSx for ONTAPファイル システムを管理するために必要な認証情報を持たないクラスターを選択した場合は、必要な権限を持つ認証情報を選択するように求めるプロンプトが表示されます。
* 次のリージョンは検出がサポートされていません: 中国リージョン、GovCloud (米国) リージョン、Secret Cloud、Top Secret Cloud。


====
.結果
コンソールの「システム」ページに、検出された FSx for ONTAPファイル システムが表示されます。 FSx for ONTAPファイルシステムは、 NetApp Consoleのワークロード、 ONTAP System Manager、AWS CloudFormation など、いくつかの方法で管理できます。。 link:task-manage-fsx-systems.html["FSx for ONTAPファイルシステムを管理する"] 。
